# Generated by Django 5.0 on 2023-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Card_Number', models.CharField(max_length=200)),
                ('Pin', models.CharField(max_length=20)),
                ('Balance', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ATM',
            },
        ),
    ]
