# Generated by Django 5.0 on 2023-12-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_atm_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='Balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
